### PR TITLE
Stress, force and drag

### PR DESCRIPTION
**Pull request by bartdavids**
Hi, I have another contribution for the LB method!

This time it goes into stress and force (and the drag coefficients). I made it using [Colab](https://colab.research.google.com/drive/1oryCdOPXapOWxGSgCDNkvSUQ_MahfoRX?usp=sharing).

Hope it helps!

### CODE REVIEW

**Comment by Ceyron** [comment]
Hi Bart,
thanks for the PR :). I didn't forget about it and will take a look at it later today or tomorrow.

**Comment by Ceyron** [comment]
Hi Bart,
I now had some time to look at it. Great work figuring out how the stress/drag calculation works. :+1: 

I must admit, I am not familiar with these advanced aspects in LBM, so it's hard to say if there might be some bug in it. Though, I was able to make it run on my machine, and it seems to work reasonably :+1:. I am certain, that this is an amazing resource for anyone interested in LBM with JAX, good job  ☺️

I would love to merge. Before that, could you do the following:

1. The link to Colab, that you provide in the file ( https://colab.research.google.com/drive/1oryCdOPXapOWxGSgCDNkvSUQ_MahfoRX?usp=sharing ) is apparently not public. Could you turn it into a public Colab Notebook?
2. For the script (and the code to be merged into the Repo):
2.1. Could you move all the constants (i.e., everything in caps) to a global scope, i.e., outside of the main function
2.2. Could you make the plotting calls (to Matplotlib) non-blocking. It took my some time to figure out that the plt.show() calls you have in the beginning and also in the time-loop block the execution of the file. One has to manually close the plotting windows each time. I assume this is not the case on Colab and you therefore left it in. I would love to have it in a way that a user can just execute the script and the plots interactively update. You could, for instance, realize this by using [plt.draw](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.draw.html). To this end, you could also merge all the different plots into one figure by [plt.subplots](https://matplotlib.org/3.5.0/api/_as_gen/matplotlib.pyplot.subplots.html).
3. Probably you have this in the Colab, but could you also add some small comments on how the strain_rate function and the get_stress function below is working. What is the motivation?

Except for these minor things, again, thanks for the contribution.  ❤️

**Comment by Ceyron** [comment]
Sorry, I accidentally pushed into the PR branch.

**Comment by Ceyron** [comment]
Hi Bart,
thanks for the modifications (and the nice added Doc-String). I was able to get it to run on my machine. On top of your changes, I made two more:

1. The interactive drawing of Matplotlib did not work for me somehow (I just executed the Python file as is and nothing was popping up except for the geometry plots in the beginning). Hence, I changed the interactive plotting to the way I would implement it.
2. I commented out the geometry display in the beginning to directly start the main simulation loop.

Let me know if you are fine with these changes, then I will merge it in :)

Thanks also for the n

**Comment by bartdavids** [comment]
Sounds great!

**Comment by Ceyron** [comment]
Beautiful :+1: 
Thanks again for the contribution. I will link to the files you created under the LBM video.

**Pull request merged**
